[customizations.installer.kickstart]
contents = """
graphical
timezone Asia/Seoul

ignoredisk --only-use={{ inputs.default_disk }}
clearpart --all --initlabel --drives={{ inputs.default_disk }}
autopart --type=plain

user --name={{ secret.DEFAULT_USER_NAME }} --uid=1000 --groups=wheel --password {{ secret.DEFAULT_USER_PASSWD }} --plaintext

%post
echo "$(hostnamectl -j | jq -r .Chassis)-$(hostnamectl -j | jq -r .MachineID | cut -c 1-9)" | tee /etc/hostname > /dev/null
%end

reboot
"""
