[customizations.installer.kickstart]
contents = """
graphical
timezone Asia/Seoul

ignoredisk --only-use={{ inputs.default_disk }}
clearpart --all --initlabel --drives={{ inputs.default_disk }}
autopart --type=plain

user --name=ytjin --uid=1000 --groups=wheel --password ${{ secret.default_user_password }} --plaintext
gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/backgrounds/custom/custom-wallpaper.jpg'

reboot

%post --erroronfail
systemctl enable docker
%end
"""
