name: "Build OCI container"
run-name: "Build bootc - ${{ github.ref }}"

on:
  workflow_dispatch:
    inputs:
      runner-group:
        description: 'Type the runner group'
        required: true
        default: 'private-runners-yuntae'
        type: string
      runner-label:
        description: 'Type label of runner'
        required: true
        default: 'ytminipc001'
        type: string
      oci_registry:
        description: 'Type the OCI registry you want to use. e.g. `ghcr.io`, `quay.io`,`docker.io`'
        required: true
        default: 'quay.io'
        type: string
      oci_image_repo:
        description: 'Type the image repository path in OCI registry you want to push (`{tenancy-namespace}/{repo-name}`)'
        required: true
        default: 'teamthepioneers/immutable-os-bootc'
        type: string
      oci_image_tag:
        description: 'Type the image tag you want to use'
        required: true
        default: 'latest'
        type: string

jobs:
  build-oci-bootc-image:
    runs-on:
      group: ${{ inputs.runner-group }}
      labels:
        - ${{ inputs.runner-label }}

    steps:
      - name: Check requirements
        run: |
          make --version &> /dev/null || { echo "Make is not installed"; exit 1; }
          sudo podman --version &> /dev/null || { echo "no podman or no permission to run podman in root"; exit 1; }

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to OCI Registry
        run: |
          podman login -u=${{ secrets.OCI_REGISTRY_BOT_USERNAME }} -p=${{ secrets.OCI_REGISTRY_BOT_PASSWORD }} ${{ inputs.oci_registry }}

      - name: Build OCI image
        run: |
          make build-oci-bootc-image \
            OCI_REGISTRY=${{ inputs.oci_registry }} \
            OCI_IMAGE_REPO=${{ inputs.oci_image_repo }} \
            OCI_IMAGE_TAG=${{ inputs.oci_image_tag }}
        env:
          OCI_REGISTRY: ${{ inputs.oci_registry }}
          OCI_IMAGE_REPO: ${{ inputs.oci_image_repo }}
          OCI_IMAGE_TAG: ${{ inputs.oci_image_tag }}

      - name: Push OCI image to registry
        run: |
          make push-oci-image \
            OCI_REGISTRY=${{ inputs.oci_registry }} \
            OCI_IMAGE_REPO=${{ inputs.oci_image_repo }} \
            OCI_IMAGE_TAG=${{ inputs.oci_image_tag }}
        env:
          OCI_REGISTRY: ${{ inputs.oci_registry }}
          OCI_IMAGE_REPO: ${{ inputs.oci_image_repo }}
          OCI_IMAGE_TAG: ${{ inputs.oci_image_tag }}
